### ISSUE TITLE
autoplay doesn't work when start, only work when i click nev/prev one time

### ISSUE THREAD

**Issue by lPaths** [leandrowd/react-responsive-carousel#298]
here are my option:
              autoPlay={true}
              interval={2000}
              infiniteLoop={true}
and it seems doesn't work correctly, please help!

**Comment by bernagl** [comment]
Im having the same error the only fix atm is install an older version and works like a charm.

but i install an older version of react-responsive-carousel and works well.

**Comment by bernagl** [comment]
Im having the same error the only fix atm is install an older version and now works like a charm.

Downgraded from `^3.1.45` to `3.1.33`

**Comment by lPaths** [comment]
> Im having the same error the only fix atm is install an older version and works like a charm.
> 
> Downgraded from `^3.1.45` to `3.1.33`

it works, thank you.

**Comment by leandrowd** [comment]
It was fixed in the latest version. Feel free to update to 3.1.46

**Comment by Sujithkumara** [comment]
I have the same issue where the carousel does not start rotating on page load. Is this fixed ? What's the workaround for this? i am using 3.1.47 version

**Comment by deepalijain1** [comment]
I am also facing the same issue. autoplay not working even in latest release which is 3.1.49 and yes, autoplay works in version 3.1.33 but when it comes to the last slide, it flips to the first one , scrolling backwards, navigating all the slides in between, which is not a very good user experience. Not sure, how it is working fine in Demos. :( Am I missing something here? please advise.

here are the options, I am using:
autoPlay={true}
infiniteLoop={true}

**Comment by leomotta121** [comment]
Same problem on ^3.1.50

**Comment by hiradyazdan** [comment]
This issue still happens and is replicable in the project examples.

**Comment by hiradyazdan** [comment]
@leandrooriente I had some time to work on above mentioned issue and I realized my comment was not quite spot on, and discovered that the actual problem is that in `componentDidUpdate`, `setupAutoPlay` uses the state before autoplay is set, so it won't recognize the `autoplay` changed and as a result it won't call the increment method on `autoPlay` function. So, `setupAutoPlay` needs to be invoked on a callback in `setState`.

Also second issue is autoPlay won't work on a time interval if it's not reseted in `moveTo` function, unless `isMouseEntered: false` state was set, so that `resetAutoPlay` method can be reached and called in `moveTo` function.

So, to wrap up this issue can be resolved by modifying the `componentDidUpdate` to the following:

```js
....
...
..
.
if (prevProps.autoPlay !== this.props.autoPlay) {
	if (this.props.autoPlay) {

		this.setState({ autoPlay: this.props.autoPlay, isMouseEntered: false }, () => {
			this.setupAutoPlay()
		})
	} else {
		this.destroyAutoPlay()

		this.setState({ autoPlay: this.props.autoPlay })
	}
}
```

I have patched the method on my end and it works fine when I need to stop the autoplay on opening a modal and start again as normal once the modal is closed.

**Comment by fredsvanelli** [comment]
Still doesn't work on the latest version so far (3.2.10).

A workaround that worked for me was not to render the Carousel until the slides are loaded:

```
return (
    <>
      {slides.length > 0 && (
        <Carousel
          infiniteLoop
          autoPlay
          stopOnHover
          interval={5000}
        >
          {slides}
        </Carousel>
      )}
    </>
  );
```

**Comment by Mihail-Shch** [comment]
Autoplay still doesn't work on 3.2.11

**Comment by johnsonfash** [comment]
just add autoFocus={true} solved the issue

**Comment by sb-hyejin** [comment]
Same problem on ^3.2.23

**Comment by siddhesh1051** [comment]
> {slides.length > 0 &&

Thanks it works fine

**Comment by FaisalSaeed-del** [comment]
use this code in your app ,its working for me
useEffect(() => {
  const interval = setInterval(() => {
      setActiveSlideIndex((activeSlideIndex + 1) % 10);
  }, 3000);
  return () => clearInterval(interval);
}, [activeSlideIndex]);

**Comment by Nitin-grappus** [comment]
> 

This worked, Thanks

**Comment by ghost** [comment]
> just add autoFocus={true} solved the issue

This worked, Thanks

**Comment by gahette** [comment]
It doesn't work on the last version 3.2.23
@fredsvanelli 
Thanks it works well for me

**Comment by jinay-kothari** [comment]
> Still doesn't work on the latest version so far (3.2.10).
> 
> A workaround that worked for me was not to render the Carousel until the slides are loaded:
> 
> ```
> return (
>     <>
>       {slides.length > 0 && (
>         <Carousel
>           infiniteLoop
>           autoPlay
>           stopOnHover
>           interval={5000}
>         >
>           {slides}
>         </Carousel>
>       )}
>     </>
>   );
> ```

this worked for me also, Thanks 👍 :)
